[template]
src         = "storm.yaml.tmpl"
dest        = "/usr/share/storm/conf/storm.yaml"
owner       = "root"
group       = "root"
mode        = "0644"
prefix      = "/services/zookeeper"
keys        = [ "/" ]
reload_cmd  = "/opt/restart-nimbus.sh"
